### ISSUE TITLE
custom field loses format type after restart and cannot be renamed

### ISSUE THREAD

**Issue by movingwater** [locaal-ai/scoresight#22]
When exporting a config file and importing it on a fresh install, the fields in the list are missing. They are fine in the viewer. Can be selected in the viewer but not able to change settings.

Maybe its related to this bug: After closing and reopening scoresight the format type of custom fields getting lost and had to be reset. 

Maybe also related: Fields that are not added to the scene cannot be renamed. I can double click on a field in the list and the rename popup opens. Then I can rename it, but after closing the renaming doesn't take effect. Only fields added to the scene can be renamed properly.

**Comment by royshil** [comment]
the loading of custom boxes has been fixed #23 
but the other two issues have not: Custom box format type and Renaming custom box

**Comment by royshil** [comment]
fixed in v0.0.11
