### ISSUE TITLE
Updates/s does not load correctly on start

### ISSUE THREAD

**Issue by royshil** [locaal-ai/scoresight#24]
After setting updates/s and closing the program, when opening the program again it updates the slider but not the actual FPS

**Comment by ArieR1963** [comment]
Hi Roy,
[Date-Time-        2024-07-26 17-38-53.200 +02001.pdf](https://github.com/user-attachments/files/16393918/Date-Time-.2024-07-26.17-38-53.200.%2B02001.pdf)

I still have the same problem?

**Comment by royshil** [comment]
fixed in #35
