### ISSUE TITLE
vMix integration not working

### ISSUE THREAD

**Issue by FabrizioBocci** [locaal-ai/scoresight#25]
Hello, i can't make it work with vMix. TCP API should be available on port 8099, i can telnet into localhost port 8099 but the software it doesn't work. I have followed your tutorial strictly.

I noticed TCP API is used: please consider using HTTP API instead which seems to be more reliable. Other products like Universal Time Controller are using them successfully.

I have made it work using Putty as telnet on port 8099 and sending SetText command, so it should be someting wrong in the software

**Comment by royshil** [comment]
thanks for the ticket - this had been reported several times.
i'm investigating the source of the bug

**Comment by royshil** [comment]
@FabrizioBocci this shuold now be resolved in the released version

**Comment by royshil** [comment]
resolved

**Comment by ArieR1963** [comment]
I try to get the VMix API working in the last version, but without any success. I download Scoreboard OCR and that works. With port localhost 8099 and right input en right names, do you have more complains with the last version?

**Comment by rickvoskamp** [comment]
Arie, are you sure you're using the correct port? Default port for the vMix-API is 8088?

**Comment by ArieR1963** [comment]
Hi Rick, Yes i'm sure for Scoreboard info you need port 8099, look at the instructions and on Scoreboard OCR it works!
You use an other port for Scoreboard - VMix API?

**Comment by rickvoskamp** [comment]
https://github.com/locaal-ai/scoresight/blob/main/docs/vmix.md

**Comment by ArieR1963** [comment]
i follow the document but without success, see my attached log files.
[scoresight_2024-12-05_00-15-43.log](https://github.com/user-attachments/files/18015302/scoresight_2024-12-05_00-15-43.log)
[scoresight_std_2024-12-05_00-15-43.log](https://github.com/user-attachments/files/18015318/scoresight_std_2024-12-05_00-15-43.log)

**Comment by ArieR1963** [comment]
i change the port to 8088 and now it works!!

**Comment by rickvoskamp** [comment]
> i change the port to 8088 and now it works!!

A great! Fijn Arie! 😀
