### ISSUE TITLE
Downs & Yards

### ISSUE THREAD

**Issue by FbgLive** [locaal-ai/scoresight#32]
Feature request: A "template" called "Down_Yards" that reads output from Down and Yards fields put into one output e.g. "{{down}} & {{yards}}".

**Comment by royshil** [comment]
implemented in #34

**Comment by royshil** [comment]
@FbgLive you will find download links here https://github.com/locaal-ai/scoresight/actions/runs/10773626500 scroll to the bottom

**Comment by royshil** [comment]
done
